"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, Bot, CheckCircle2, Download, FileCheck2, Info, ShieldAlert } from "lucide-react";
import { useParams } from "next/navigation";
import { FormEvent, useState } from "react";
import { EmptyState, ErrorState, LoadingState, Section } from "@/components/ui";
import { api } from "@/lib/api";
import { boolLabel, inr, number, text } from "@/lib/format";
import { Row, asRecord, asRows, attentionLabel, complianceState, documentStateLabel, familyExplanation, familyLabel, formatFact, formatMetric, humanizeNarrative, metricLabel } from "@/lib/presentation";
import { useScope } from "@/lib/scope";

const SECTION_LINKS = [["overview", "Case Overview"], ["attention", "Why Attention"], ["warnings", "Early Warnings"], ["payments", "Payments & Progress"], ["timeline", "Timeline"], ["compliance", "Compliance"], ["duplicates", "Duplicate Review"], ["peer", "Similar Works"], ["forecast", "Forecast"], ["trends", "Trends"], ["brief", "AI Case Assessment"], ["review", "Officer Review"]] as const;
const STATE_LABELS: Record<string, string> = { strong_issue: "Observed strong issue", review: "Requires Review", analytical: "Analytical signal", context: "Context", pass: "Normal", not_applicable: "Not yet applicable", insufficient: "Insufficient data" };

function StatePill({ state, label }: { state: string; label?: string }) {
  const Icon = state === "strong_issue" ? ShieldAlert : state === "pass" ? CheckCircle2 : state === "context" ? Info : AlertTriangle;
  return <span className={`state-pill state-${state}`}><Icon size={12} />{label ?? STATE_LABELS[state] ?? state}</span>;
}
function WorkBand({ value }: { value: unknown }) { const band = String(value ?? "UNKNOWN"); return <span className={`band band-${band.toLowerCase()}`}>{band}</span>; }
function TechnicalDetails({ children, label = "Technical details" }: { children: React.ReactNode; label?: string }) { return <details className="technical-details"><summary>{label}</summary><div>{children}</div></details>; }
function Field({ label, value, money = false, suffix, highlight }: { label: string; value: unknown; money?: boolean; suffix?: string; highlight?: Row }) {
  const rendered = money && typeof value === "number" ? inr.format(value) : typeof value === "boolean" ? boolLabel(value) : `${text(value)}${value !== null && value !== undefined && value !== "" ? suffix ?? "" : ""}`;
  const state = String(highlight?.state ?? "");
  return <div className={`profile-field ${state ? `field-${state}` : ""}`}><dt>{label}</dt><dd>{rendered}</dd>{state && <small><StatePill state={state} label={text(highlight?.reason)} /></small>}</div>;
}
function ReviewNote() { return <div className="review-note"><strong>Review Note</strong><p>This assessment is intended to support authorized human review. It summarizes recorded project data, deterministic MPLADS rule checks and analytical signals. The observations do not by themselves establish fraud, misuse, corruption or wrongdoing. Any administrative, financial or legal conclusion must be based on verification of authoritative records, approved revisions and applicable procedures.</p></div>; }
function ComplianceCard({ rule }: { rule: Row }) {
  const state = complianceState(rule.result);
  return <article className={`compliance-card state-border-${state}`}><div className="card-title"><h3>{text(rule.rule_title)}</h3><StatePill state={state} label={text(rule.result) === "NON_COMPLIANT" ? "Non-Compliant" : text(rule.result) === "REVIEW" ? "Requires Review" : text(rule.result).replaceAll("_", " ")} /></div><div className="rule-grid"><div><span>Observed</span><p>{text(rule.observed_value)}</p></div><div><span>Expected</span><p>{text(rule.expected_condition)}</p></div></div><p><strong>Why:</strong> {text(rule.evidence)}</p><p><strong>Officer should verify:</strong> the cited source records, guideline condition, and any permitted exception.</p><div className="citation">MPLADS clause {text(rule.guideline_clause)} · page {text(rule.guideline_page)}</div><TechnicalDetails><p>Rule <code>{text(rule.rule_id)}</code> · chunk <code>{text(rule.guideline_chunk_ids)}</code> · source <code>{text(rule.source_artifact)}</code></p></TechnicalDetails></article>;
}
function PeerCard({ row }: { row: Row }) {
  const metric = String(row.metric ?? "");
  return <article className="peer-card state-border-analytical"><div className="card-title"><div><span className="card-kicker">Strongest difference</span><h3>{text(row.label, metricLabel(metric))}</h3></div><StatePill state="analytical" label={text(row.comparison)} /></div><div className="comparison-grid"><div><span>This work</span><strong>{formatMetric(metric, row.observed_value)}</strong></div><div><span>Typical similar work</span><strong>{formatMetric(metric, row.peer_median)}</strong></div><div><span>Comparison</span><strong>{text(row.comparison)}</strong></div><div><span>Compared with</span><strong>{number.format(Number(row.peer_group_size ?? 0))} similar works</strong></div></div><p><strong>Why it matters:</strong> {text(row.why_it_matters)}</p><TechnicalDetails><pre>{JSON.stringify(row.technical, null, 2)}</pre></TechnicalDetails></article>;
}
function ProgressComparison({ physical, financial }: { physical: number | null; financial: number | null }) {
  if (physical === null || financial === null) return <EmptyState label="No paired physical and financial progress values are available." />;
  const scale = Math.max(100, Math.ceil(Math.max(physical, financial) / 20) * 20);
  return <div className="progress-comparison"><div className="progress-scale"><span>0%</span><span>Shared scale: {scale}%</span></div>{[["Physical progress", physical, "physical"], ["Financial progress", financial, "financial"]].map(([label, value, kind]) => <div className="progress-line" key={String(kind)}><div className="progress-label"><span>{label}</span><strong>{number.format(Number(value))}%</strong></div><div className="progress-track"><span className={`progress-fill progress-${kind}`} style={{ width: `${Math.max(0, Number(value) / scale * 100)}%` }} /></div></div>)}</div>;
}
function Assessment({ assessment, narrative, generated }: { assessment: Row; narrative: Row; generated: boolean }) {
  const project = asRecord(assessment.project), finance = asRecord(assessment.financial_and_payment), schedule = asRecord(assessment.progress_and_schedule), trend = asRecord(assessment.operational_context);
  const observations = asRows(assessment.main_observations), rules = asRows(assessment.compliance_checks), peers = asRows(assessment.peer_comparisons), duplicates = asRows(assessment.duplicate_review);
  return <div className="case-assessment">
    <article className="assessment-section"><b>1</b><div><h3>Project</h3><h4>{text(project.work_title)}</h4><p>{text(project.work_id)} · {text(project.location)} · {text(project.lifecycle)}</p><p>Review Priority {number.format(Number(project.review_priority_score ?? 0))}/100 ({text(project.review_priority_band)}) · {attentionLabel(project.attention_level)}</p></div></article>
    <article className="assessment-section"><b>2</b><div><h3>Executive Review Summary</h3><p>{generated && narrative.summary ? humanizeNarrative(narrative.summary) : text(assessment.executive_summary)}</p></div></article>
    {observations.length > 0 && <article className="assessment-section"><b>3</b><div><h3>Main Observations Requiring Attention</h3>{observations.map((issue, index) => <div className={`assessment-issue state-border-${text(issue.state)}`} key={`${text(issue.title)}-${index}`}><div className="card-title"><h4>Issue {index + 1} — {text(issue.title)}</h4><StatePill state={text(issue.state)} label={text(issue.severity_label)} /></div><p>{text(issue.summary)}</p>{asRows(issue.key_facts).length > 0 && <div className="key-facts">{asRows(issue.key_facts).map((fact) => <div key={text(fact.label)}><span>{text(fact.label)}</span><strong>{formatFact(fact.value, fact.format)}</strong></div>)}</div>}<p><strong>Why it needs attention:</strong> {text(issue.why_attention)}</p><p><strong>What to verify:</strong> {text(issue.officer_verification)}</p><TechnicalDetails label="Evidence & Supporting Records"><pre>{JSON.stringify(issue.technical_reference, null, 2)}</pre></TechnicalDetails></div>)}</div></article>}
    <article className="assessment-section"><b>4</b><div><h3>Financial &amp; Payment Findings</h3><dl className="data-list"><Field label="Sanctioned amount" value={finance.sanctioned_amount_inr} money /><Field label="Released payments" value={finance.released_payments_inr} money /><Field label="Recorded difference" value={finance.difference_inr} money /><Field label="Amount above sanction" value={finance.percentage_above_sanction} suffix="%" /></dl>{Boolean(finance.authorization_date) && <p>Authorization is recorded on {formatFact(finance.authorization_date, "date")}; the request is recorded on {formatFact(finance.request_date, "date")}.</p>}</div></article>
    <article className="assessment-section"><b>5</b><div><h3>Progress / Schedule Findings</h3><dl className="data-list"><Field label="Physical progress" value={schedule.physical_progress_pct} suffix="%" /><Field label="Financial progress" value={schedule.financial_progress_pct} suffix="%" /><Field label="Difference" value={schedule.gap_percentage_points} suffix=" percentage points" /><Field label="Expected completion" value={schedule.expected_completion_date} /><Field label="Completion recorded" value={schedule.completion_date} /><Field label="Analytical snapshot" value={schedule.snapshot_date} /></dl></div></article>
    {rules.length > 0 && <article className="assessment-section"><b>6</b><div><h3>MPLADS Rule Checks</h3>{rules.map((rule) => <div className="brief-rule" key={text(rule.rule_id)}><h4>{text(rule.title)}</h4><StatePill state={text(rule.status) === "Non-Compliant" ? "strong_issue" : "review"} label={text(rule.status)} /><p><strong>Observed:</strong> {text(rule.observed)}</p><p><strong>Expected:</strong> {text(rule.expected)}</p><TechnicalDetails label="Evidence & References"><p>Clause {text(rule.clause)} · page {text(rule.page)} · rule <code>{text(rule.rule_id)}</code> · chunk <code>{text(rule.chunk_ids)}</code></p></TechnicalDetails></div>)}</div></article>}
    {duplicates.length > 0 && <article className="assessment-section"><b>7</b><div><h3>Duplicate Review</h3><p>A corroborated candidate needs side-by-side file review. This does not confirm that the works are the same.</p></div></article>}
    {peers.length > 0 && <article className="assessment-section"><b>8</b><div><h3>Comparison With Similar Works</h3>{peers.slice(0, 3).map((row) => <p key={text(row.metric)}>{text(row.label)} is <strong>{text(row.comparison).toLowerCase()}</strong> among {text(row.peer_group_size)} comparable works. This analytical signal does not establish wrongdoing.</p>)}</div></article>}
    {trend.has_supported_deviation === true && <article className="assessment-section"><b>9</b><div><h3>Supporting Operational Context</h3><p>{text(trend.title)} is {text(trend.assessment).toLowerCase()}. This surrounding context is not direct evidence against this work.</p></div></article>}
    {generated && asRows(narrative.why_flagged).length > 0 && <article className="assessment-section"><b>AI</b><div><h3>Grounded Provider Assessment</h3>{asRows(narrative.why_flagged).map((item, index) => <div className="brief-rule" key={index}><h4>{text(item.title, `Grounded observation ${index + 1}`)}</h4><p>{humanizeNarrative(item.finding)}</p><TechnicalDetails label="Evidence & References"><pre>{JSON.stringify(item, null, 2)}</pre></TechnicalDetails></div>)}</div></article>}
    <article className="assessment-section"><b>10</b><div><h3>What the Officer Should Verify</h3><div className="verification-checklist">{(Array.isArray(assessment.verification_steps) ? assessment.verification_steps : []).map((item) => <label key={String(item)}><input type="checkbox" />{String(item)}</label>)}</div></div></article>
  </div>;
}

export default function WorkDetailPage() {
  const { workId } = useParams<{ workId: string }>(); const { scope } = useScope(); const client = useQueryClient();
  const query = useQuery({ queryKey: ["work", workId], queryFn: () => api.work(workId) });
  const [explanation, setExplanation] = useState<Row | null>(null);
  const explain = useMutation({ mutationFn: () => api.explain(workId, true), onSuccess: setExplanation });
  const review = useMutation({ mutationFn: (payload: Record<string, string>) => api.addReview(workId, payload), onSuccess: () => client.invalidateQueries({ queryKey: ["work", workId] }) });
  const [status, setStatus] = useState("IN_REVIEW"), [actor, setActor] = useState(""), [note, setNote] = useState("");
  if (query.isLoading) return <LoadingState label="Loading complete work dossier…" />;
  if (query.error || !query.data) return <ErrorState error={query.error} />;
  const d = query.data, p = d.profile, priority = d.priority, presentation = asRecord(d.presentation);
  const highlights = asRecord(presentation.highlighted_fields), financial = asRecord(presentation.financial), chronology = asRecord(presentation.payment_chronology), timeline = asRecord(presentation.timeline), readiness = asRecord(presentation.document_readiness), trend = asRecord(presentation.trend), assessment = asRecord(presentation.case_assessment);
  const peer = asRecord(d.peer_benchmark), duplicates = asRecord(d.duplicates), payments = asRecord(d.payments), compliance = asRecord(d.compliance), prediction = asRecord(d.prediction), scores = asRecord(prediction.scores);
  const currentExplanation = explanation ?? asRecord(d.explanation), narrative = asRecord(currentExplanation.explanation);
  const contributions = [...d.contributions].filter((row) => Number(row.contribution_points ?? 0) > 0).sort((a, b) => Number(b.contribution_points ?? 0) - Number(a.contribution_points ?? 0));
  const warnings = asRows(presentation.warning_signals), rules = asRows(compliance.rules), actionableRules = rules.filter((r) => ["NON_COMPLIANT", "REVIEW"].includes(String(r.result))), ordinaryRules = rules.filter((r) => !["NON_COMPLIANT", "REVIEW"].includes(String(r.result))), counts = asRecord(presentation.compliance_counts);
  const physical = typeof financial.physical_progress_pct === "number" ? financial.physical_progress_pct : null, financialProgress = typeof financial.financial_progress_pct === "number" ? financial.financial_progress_pct : null;
  const mode = String(currentExplanation.generation_mode ?? "DETERMINISTIC_FALLBACK"), provider = String(currentExplanation.api_status ?? "OFFLINE_DEFAULT"), badge = mode === "GROQ_GROUNDED" ? "GROQ GROUNDED" : "LOCAL DETERMINISTIC FALLBACK";
  const submitReview = (event: FormEvent) => { event.preventDefault(); review.mutate({ actor_role: scope.role, actor_label: actor, status, note }); };
  return <>
    <header className="case-header"><div><p className="eyebrow">Officer case workspace</p><h1>{text(p.work_description)}</h1><p>{workId} · {text(p.village)}, {text(p.block)}, {text(p.district)}, {text(p.state_name)}</p><span className={`attention-badge attention-${text(presentation.attention_level).toLowerCase()}`}>{attentionLabel(presentation.attention_level)}</span>{presentation.requires_review === true && <span className="requires-review">Requires Review</span>}</div><div className="priority-lockup"><span>Governed Review Priority</span><strong>{number.format(Number(priority.review_priority_score_0_100 ?? 0))}<small>/100</small></strong><WorkBand value={priority.review_priority_band} /></div></header>
    <div className="priority-disclaimer"><Info size={16} /><span>Review Priority indicates review urgency, not evidence of wrongdoing.</span></div>
    <nav className="section-nav" aria-label="Work detail sections">{SECTION_LINKS.map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav>

    <Section id="overview" title="Case at a Glance / Case Overview" subtitle="Authoritative record with lifecycle-aware completion expectations"><div className="overview-grid"><div><h3>Main Attention Areas</h3><div className="attention-list">{(presentation.main_attention_areas as string[]).map((item) => <span key={item}><AlertTriangle size={14} />{item}</span>)}</div></div><dl className="case-facts"><Field label="Work ID" value={workId} /><Field label="Lifecycle" value={p.lifecycle_stage} /><Field label="Recorded work status" value={p.source_current_status} /><Field label="Officer case status" value={d.current_review_status} /></dl></div><dl className="data-list profile-data"><Field label="MP" value={`${text(p.mp_name)} (${text(p.mp_id)})`} /><Field label="Constituency" value={p.constituency} /><Field label="Location" value={`${text(p.village)}, ${text(p.block)}, ${text(p.district)}, ${text(p.state_name)}`} /><Field label="Sector / sub-sector" value={`${text(p.sector)} / ${text(p.sub_sector)}`} /><Field label="Implementing agency" value={`${text(p.implementing_agency_name)} (${text(p.implementing_agency_id)})`} /><Field label="Recommended amount" value={p.recommended_amount_inr} money /><Field label="Technical estimate" value={p.technical_estimate_amount_inr} money /><Field label="Sanctioned amount" value={p.sanctioned_amount_inr} money highlight={asRecord(highlights.sanctioned_amount_inr)} /><Field label="Released payments" value={p.released_payment_total_inr_as_of} money highlight={asRecord(highlights.released_payment_total_inr_as_of)} /><Field label="Current expenditure" value={p.cumulative_expenditure_inr_as_of} money /><Field label="Final expenditure" value={p.final_expenditure_inr_as_of} money /><Field label="Expected completion" value={p.expected_completion_date} highlight={asRecord(highlights.expected_completion_date)} /><Field label="Physical progress" value={p.latest_physical_progress_pct_as_of} suffix="%" /><Field label="Financial progress" value={p.latest_financial_progress_pct_as_of} suffix="%" /></dl><div className="readiness-block"><h3>Records &amp; Completion Readiness</h3><p>{text(readiness.headline)}</p><div className="readiness-grid">{asRows(readiness.entries).map((entry) => <article className={`readiness-item state-border-${text(entry.state)}`} key={text(entry.key)}><span>{text(entry.label)}</span><strong>{documentStateLabel(entry.status_code)}</strong><StatePill state={text(entry.state)} label={text(entry.status_label)} /><TechnicalDetails><p>Observed value: {text(entry.source_value)} · rule <code>{text(entry.rule_id)}</code> · result <code>{text(entry.rule_result)}</code></p></TechnicalDetails></article>)}</div></div><TechnicalDetails label="View full source profile"><dl className="data-list">{Object.entries(p).map(([key, value]) => <Field key={key} label={key.replaceAll("_", " ")} value={value} />)}</dl></TechnicalDetails></Section>

    <Section id="attention" title="Why This Work Needs Attention" subtitle="Transparent composition of the frozen Day-7 Review Priority"><div className="score-explainer"><div className="score-ring"><strong>{number.format(Number(priority.review_priority_score_0_100))}</strong><span>of 100</span></div><div><h3>{attentionLabel(presentation.attention_level)}</h3><p>The score combines governed signal families for this lifecycle. It is not a probability of wrongdoing.</p></div></div><div className="driver-grid">{contributions.slice(0, 3).map((row, index) => <article className="driver-card" key={String(row.family)}><span className="driver-rank">#{index + 1} contributor</span><h3>{familyLabel(row.family)}</h3><strong>{number.format(Number(row.contribution_points))} <small>of {number.format(Number(row.family_weight_pct))} possible</small></strong><p>{familyExplanation(row.family)}</p><TechnicalDetails><p>{text(row.evidence_summary)}</p><p>Family <code>{text(row.family)}</code> · score {text(row.family_score_0_100)} · source {text(row.source_artifact)} · evidence {text(row.evidence_code)}</p></TechnicalDetails></article>)}</div><div className="reconciliation-line"><CheckCircle2 size={16} />All family contributions reconcile exactly to the governed score: <strong>{text(d.contribution_sum)}</strong></div></Section>

    <Section id="warnings" title="Early Warnings & Review Signals" subtitle="Each card separates observed facts, analytical signals, and operational context">{warnings.length ? <div className="warning-groups">{warnings.map((row, index) => <article className={`warning-card state-border-${text(row.state)}`} key={index}><div className="card-title"><div><span className="card-kicker">{text(row.category)}</span><h3>{text(row.title)}</h3></div><StatePill state={text(row.state)} label={text(row.severity_label)} /></div><p className="warning-summary">{text(row.summary)}</p><div className="key-facts">{asRows(row.key_facts).map((fact) => <div key={text(fact.label)}><span>{text(fact.label)}</span><strong>{formatFact(fact.value, fact.format)}</strong></div>)}</div><p><strong>Why this needs attention:</strong> {text(row.why_attention)}</p><p><strong>Officer should verify:</strong> {text(row.officer_verification)}</p><TechnicalDetails><pre>{JSON.stringify(row.technical_reference, null, 2)}</pre></TechnicalDetails></article>)}</div> : <div className="normal-callout"><CheckCircle2 size={17} /><strong>Normal — no current review signal is present.</strong></div>}</Section>

    <Section id="payments" title="Payments & Work Progress" subtitle="Visible amounts and progress remain separate from one-to-many source records"><div className="financial-summary"><div><span>Sanctioned</span><strong>{formatFact(financial.sanctioned_amount_inr, "currency")}</strong></div><div><span>Released</span><strong>{formatFact(financial.released_payments_inr, "currency")}</strong></div><div><span>Difference</span><strong>{formatFact(financial.released_minus_sanction_inr, "currency")}</strong></div><div><span>Payment count</span><strong>{number.format(Number(p.released_payment_count_as_of ?? 0))}</strong></div></div>{financial.released_exceeds_visible_sanction === true ? <div className={`financial-callout state-border-${text(asRecord(financial.exceedance_display_severity).state)}`}><ShieldAlert size={19} /><div><StatePill state={text(asRecord(financial.exceedance_display_severity).state)} label={text(asRecord(financial.exceedance_display_severity).label)} /><p>{number.format(Number(financial.percentage_above_sanction))}% above the visible sanction. Verify whether an approved revised sanction or authorized variation exists.</p></div></div> : <div className="normal-callout"><CheckCircle2 size={17} /><strong>Normal — released payments are within the visible sanction.</strong></div>}<div className="payment-progress-grid"><ProgressComparison physical={physical} financial={financialProgress} /><div className="gap-card"><span>Financial minus physical gap</span><strong>{formatFact(financial.financial_minus_physical_gap_percentage_points, "percentage_points")}</strong>{financial.persistent_gap === true && <><StatePill state="review" label="Persistent mismatch" /><p>This mismatch was present across multiple consecutive progress reports.</p></>}</div></div>{chronology.authorization_before_request === true ? <article className="chronology-card"><div className="card-title"><h3>Payment chronology needs verification</h3><StatePill state="review" /></div><p>Authorization is recorded on {formatFact(chronology.authorization_date, "date")}, before the payment request dated {formatFact(chronology.request_date, "date")}.</p><p><strong>Officer should verify:</strong> payment request, authorization order, and PFMS/source sequence.</p></article> : <div className="normal-callout"><CheckCircle2 size={17} /><strong>Normal — no payment chronology issue is currently flagged.</strong></div>}<TechnicalDetails label="Payment and fund-progress evidence"><pre>{JSON.stringify({ payment_evidence: payments.evidence, fund_progress: payments.fund_progress }, null, 2)}</pre></TechnicalDetails></Section>

    <Section id="timeline" title="Project Timeline & Event Checks" subtitle="Recorded and expected events are distinguished"><div className="case-timeline">{asRows(timeline.events).map((event, index) => <article className={`timeline-event timeline-${text(event.state)}`} key={index}><time>{formatFact(event.date, "date")}</time><div className="timeline-marker">{event.state === "strong_issue" ? "▲" : event.state === "review" ? "◆" : event.kind === "planned" ? "○" : "●"}</div><div><h3>{text(event.label)}</h3><span>{event.kind === "planned" ? "Planned / expected event" : "Recorded event"}</span>{Boolean(event.detail) && <p>{text(event.detail)}</p>}</div></article>)}</div></Section>

    <Section id="compliance" title="MPLADS Rule & Compliance Check" subtitle="Only deterministic rules establish compliance status"><div className="compliance-counts">{["PASS", "REVIEW", "NON_COMPLIANT", "NOT_APPLICABLE", "INSUFFICIENT_DATA"].map((result) => <div key={result}><span>{result === "NON_COMPLIANT" ? "Non-Compliant" : result === "REVIEW" ? "Requires Review" : result.replaceAll("_", " ")}</span><strong>{number.format(Number(counts[result] ?? 0))}</strong></div>)}</div>{actionableRules.length ? <div className="stack">{actionableRules.map((rule) => <ComplianceCard rule={rule} key={String(rule.rule_id)} />)}</div> : <EmptyState label="No actionable compliance issue; view all rule checks below." />}<details className="all-rules"><summary>View all other rule checks ({ordinaryRules.length})</summary><div className="stack">{ordinaryRules.map((rule) => <ComplianceCard rule={rule} key={String(rule.rule_id)} />)}</div></details><p className="section-note">Requires Review is not Non-Compliant. The two states remain distinct.</p></Section>

    <Section id="duplicates" title="Duplicate Work Review" subtitle="Candidates require comparison and are never described as confirmed duplicates">{asRows(duplicates.review_candidates).length ? asRows(duplicates.review_candidates).map((candidate) => { const paired = asRecord(candidate.paired_work); return <article className="duplicate-card" key={text(candidate.pair_id)}><div className="candidate-banner"><AlertTriangle size={17} /><strong>Duplicate Review Candidate — not confirmation that the works are the same.</strong></div><div className="pair-grid"><div><span>Current work</span><h3>{text(p.work_description)}</h3><p>{text(p.village)}, {text(p.block)}</p></div><div><span>Candidate work</span><h3>{text(paired.work_description)}</h3><p>{text(paired.village)}, {text(paired.block)}</p><a href={`/works/${text(paired.work_id)}`}>Open {text(paired.work_id)}</a></div></div><TechnicalDetails><pre>{JSON.stringify(candidate, null, 2)}</pre></TechnicalDetails></article>; }) : <div className="normal-callout"><CheckCircle2 size={17} /><strong>Normal — no corroborated duplicate candidate is currently flagged.</strong></div>}</Section>

    <Section id="peer" title="Comparison With Similar Works" subtitle="Strongest Differences From Similar Works"><div className="peer-summary"><div><span>Statistical unusualness</span><strong>{number.format(Number(d.anomaly.within_stage_anomaly_percentile_0_100 ?? 0))}th percentile</strong><small>More unusual than about this share of same-stage works</small></div><div><span>Flagged peer differences</span><strong>{asRows(presentation.peer_comparisons).length}</strong></div></div>{asRows(presentation.peer_comparisons).length ? <div className="peer-grid">{asRows(presentation.peer_comparisons).map((row) => <PeerCard row={row} key={String(row.metric)} />)}</div> : <div><StatePill state="pass" label="Normal / analytical context" /><p>No significant peer-comparison outlier is currently flagged.</p></div>}<div className="analytical-disclaimer">This is an analytical prioritization signal, not evidence of wrongdoing.</div><TechnicalDetails><pre>{JSON.stringify(peer, null, 2)}</pre></TechnicalDetails></Section>

    <Section id="forecast" title="Forecast & Early Warning" subtitle="Observed facts appear before limited-reliability predictive context"><div className="forecast-columns"><div><h3>Observed Now</h3>{scores.already_overdue_as_of === true && <article className="observed-card"><StatePill state="strong_issue" label="Observed overdue" /><p>{number.format(Number(p.overdue_days_as_of ?? 0))} days past expected completion.</p></article>}{scores.already_over_sanction_as_of !== true && scores.already_overdue_as_of !== true && <EmptyState label="No governed observed overdue or over-sanction condition is present." />}</div><div><h3>Predictive / Early Warning</h3><article className="prediction-card"><StatePill state="insufficient" label="Delay prediction unavailable" /><p>The available outcomes do not support a defensible delay classifier.</p></article>{scores.cost_overrun_serving_percentile_0_100 != null && <article className="prediction-card"><StatePill state="analytical" label="Cost-overrun early warning" /><p>Relative model signal: {number.format(Number(scores.cost_overrun_serving_percentile_0_100))}th percentile.</p><strong>Model reliability: Limited</strong></article>}</div></div><TechnicalDetails><pre>{JSON.stringify(prediction, null, 2)}</pre></TechnicalDetails></Section>

    <Section id="trends" title="Operational Trend Context" subtitle="Most unusual surrounding operational trend"><div className="trend-card"><Info size={20} /><div><span>{text(trend.group)}</span><h3>{text(trend.title)}</h3><div className="comparison-grid"><div><span>Current month</span><strong>{formatMetric(String(trend.metric ?? ""), trend.current_value)}</strong></div><div><span>Recent baseline</span><strong>Typical: {formatMetric(String(trend.metric ?? ""), trend.baseline_value)}</strong></div><div><span>Assessment</span><strong>{text(trend.assessment)}</strong></div></div><p>This describes the surrounding district/sector operational environment. It is not direct evidence against this individual work.</p></div></div><TechnicalDetails><pre>{JSON.stringify(trend.technical, null, 2)}</pre></TechnicalDetails></Section>

    <Section id="brief" title="AI-Assisted Case Assessment" subtitle="Local structured evidence by default; Groq only after an explicit request"><div className="brief-header"><div><span>Project</span><h3>{text(p.work_description)}</h3><p>{workId} · {text(p.district)}, {text(p.state_name)} · {text(p.lifecycle_stage)}</p></div><div><span>Attention</span><strong>{attentionLabel(presentation.attention_level)}</strong><small>Review Priority {number.format(Number(priority.review_priority_score_0_100))}/100 ({text(priority.review_priority_band)})</small></div></div><div className="mode-line"><StatePill state={mode === "GROQ_GROUNDED" ? "analytical" : "context"} label={badge} /><span>All quantitative facts originate in validated structured evidence.</span></div><Assessment assessment={assessment} narrative={narrative} generated={mode === "GROQ_GROUNDED"} /><ReviewNote /><div className="brief-actions"><button className="button" onClick={() => explain.mutate()} disabled={explain.isPending}><Bot size={15} />{explain.isPending ? "Preparing grounded case assessment..." : "Generate Grounded AI Explanation"}</button><a className="button secondary" href={api.caseReportUrl(workId)}><Download size={15} />Download Case Review Report</a></div>{explain.error && <p role="alert" className="inline-error">{explain.error.message}</p>}{explanation && <div className="provider-result"><CheckCircle2 size={15} /><span>{badge} · {provider}</span>{(provider.includes("429") || provider.includes("RATE")) && <p>Groq is temporarily rate-limited. The verified local assessment remains available.</p>}</div>}<TechnicalDetails><p>Mode <code>{mode}</code> · provider <code>{provider}</code></p><p>Groq is contacted only by the explicit button. Downloading a report never triggers Groq.</p></TechnicalDetails></Section>

    <Section id="review" title="Officer Review & Audit Trail" subtitle={`Current officer case status: ${d.current_review_status}`}><form className="form-grid" onSubmit={submitReview}><label>Officer / desk label<input required minLength={2} maxLength={120} value={actor} onChange={(e) => setActor(e.target.value)} /></label><label>Status<select value={status} onChange={(e) => setStatus(e.target.value)}>{["OPEN", "IN_REVIEW", "NEEDS_CLARIFICATION", "ESCALATED", "RESOLVED", "FALSE_POSITIVE"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="wide">Review note<textarea required minLength={2} maxLength={2000} value={note} onChange={(e) => setNote(e.target.value)} /></label><div className="wide"><button className="button" disabled={review.isPending}><FileCheck2 size={15} />{review.isPending ? "Recording…" : "Append review record"}</button></div></form><div className="history-block"><h3>Append-only history</h3>{d.reviews.length ? d.reviews.map((row, index) => <article className="record-card" key={String(row.review_id ?? index)}><strong>{text(row.status).replaceAll("_", " ")}</strong><p>{text(row.note)}</p><small>{text(row.actor_label)} · {text(row.actor_role)} · {text(row.created_at)}</small></article>) : <EmptyState label="No officer review has been recorded yet." />}</div></Section>
  </>;
}
